version: '3'

services:
  categorizer_service:
    build: ../services/categorizer
    ports:
      - "18888:18888"
    restart: always
    networks:
      - docker_network

  searchengine_service:
    build: ../services/searchengine
    ports:
      - "18881:18881"
    restart: always
    networks:
      - docker_network

  bot_service:
    build: ../services/bot
    ports:
      - "443:443"
    networks:
      - docker_network
    environment:
      TELEGRAM_TOKEN: YOUR_TOKEN
    restart: always
    links: 
        - searchengine_service
        - categorizer_service
        - redis

networks:
  docker_network:
    driver: bridge

volumes:
  redis_volume: