# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: categorizer.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63\x61tegorizer.proto\x12\x0b\x63\x61tegorizer\"&\n\x12GetCategoryRequest\x12\x10\n\x08question\x18\x01 \x01(\t\"<\n\x13GetCategoryResponse\x12\x10\n\x08\x63\x61tegory\x18\x01 \x01(\x05\x12\x13\n\x0bprobability\x18\x02 \x01(\x02\x32_\n\x0b\x43\x61tegorizer\x12P\n\x0bGetCategory\x12\x1f.categorizer.GetCategoryRequest\x1a .categorizer.GetCategoryResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'categorizer_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GETCATEGORYREQUEST']._serialized_start=34
  _globals['_GETCATEGORYREQUEST']._serialized_end=72
  _globals['_GETCATEGORYRESPONSE']._serialized_start=74
  _globals['_GETCATEGORYRESPONSE']._serialized_end=134
  _globals['_CATEGORIZER']._serialized_start=136
  _globals['_CATEGORIZER']._serialized_end=231
# @@protoc_insertion_point(module_scope)
