# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import lib.categorizer_pb2 as categorizer__pb2


class CategorizerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCategory = channel.unary_unary(
                '/categorizer.Categorizer/GetCategory',
                request_serializer=categorizer__pb2.GetCategoryRequest.SerializeToString,
                response_deserializer=categorizer__pb2.GetCategoryResponse.FromString,
                )


class CategorizerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetCategory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CategorizerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCategory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCategory,
                    request_deserializer=categorizer__pb2.GetCategoryRequest.FromString,
                    response_serializer=categorizer__pb2.GetCategoryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'categorizer.Categorizer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Categorizer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetCategory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/categorizer.Categorizer/GetCategory',
            categorizer__pb2.GetCategoryRequest.SerializeToString,
            categorizer__pb2.GetCategoryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
