# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: searchengine.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12searchengine.proto\x12\x0csearchengine\"6\n\x10GetAnswerRequest\x12\x10\n\x08question\x18\x01 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x02 \x01(\x05\"K\n\x11GetAnswerResponse\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t\x12\x13\n\x0bprobability\x18\x02 \x01(\x02\x12\x11\n\tanswer_id\x18\x03 \x01(\x05\x32\\\n\x0cSearchEngine\x12L\n\tGetAnswer\x12\x1e.searchengine.GetAnswerRequest\x1a\x1f.searchengine.GetAnswerResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'searchengine_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GETANSWERREQUEST']._serialized_start=36
  _globals['_GETANSWERREQUEST']._serialized_end=90
  _globals['_GETANSWERRESPONSE']._serialized_start=92
  _globals['_GETANSWERRESPONSE']._serialized_end=167
  _globals['_SEARCHENGINE']._serialized_start=169
  _globals['_SEARCHENGINE']._serialized_end=261
# @@protoc_insertion_point(module_scope)
